# Generated by Django 6.1.1 on 2026-09-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Estimated journey duration in minutes'),
        ),
    ]
