# Generated by Django 6.1.1 on 2026-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_busschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busschedule',
            options={'ordering': ['day_order', 'departure_time']},
        ),
        migrations.AddField(
            model_name='busschedule',
            name='day_order',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
