# Generated by Django 6.1.1 on 2026-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_busschedule_options_busschedule_day_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='travel_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Travel time from the previous stop in minutes'),
        ),
    ]
