# Generated by Django 6.1.1 on 2026-09-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_routestop_travel_time_minutes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='busschedule',
            constraint=models.UniqueConstraint(fields=('route', 'day', 'departure_time'), name='unique_route_day_departure'),
        ),
    ]
