# Generated by Django 6.1.1 on 2026-09-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_stop_latitude_stop_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='routes.route')),
            ],
            options={
                'ordering': ['route', 'min_distance_km'],
                'constraints': [models.UniqueConstraint(fields=('route', 'min_distance_km', 'max_distance_km'), name='unique_route_fare_slab')],
            },
        ),
    ]
