# Generated by Django 6.1.1 on 2026-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='distance_from_start_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
