# Generated by Django 6.1.1 on 2026-09-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('ORDINARY', 'Ordinary'), ('FAST', 'Fast Passenger'), ('SUPER_FAST', 'Super Fast'), ('EXPRESS', 'Express'), ('AC', 'AC')], default='ORDINARY', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
