# Generated by Django 6.1.1 on 2026-09-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction of travel in degrees', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='buses.bus')),
            ],
        ),
    ]
