# Generated by Django 6.1.1 on 2026-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_buslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='is_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
