# Generated by Django 6.1.1 on 2026-09-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_buslocation_is_tracking'),
        ('routes', '0006_busschedule_unique_route_day_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_assigned_buses', to='routes.route'),
        ),
    ]
