# Generated by Django 6.1.1 on 2026-09-19 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_bus_current_route'),
        ('routes', '0007_stop_latitude_stop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='current_route_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bus_locations', to='routes.routestop'),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='stop_arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='stop_departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='stop_status',
            field=models.CharField(choices=[('TRAVELLING', 'Travelling'), ('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed')], default='TRAVELLING', max_length=20),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='tracking_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='BusStopVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_visits', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stop_visits', to='routes.route')),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_visits', to='routes.routestop')),
            ],
            options={
                'ordering': ['-arrival_time'],
                'indexes': [models.Index(fields=['bus', 'route', 'tracking_session_id'], name='buses_busst_bus_id_79ce9d_idx')],
            },
        ),
    ]
