# Generated by Django 6.1.1 on 2026-09-21 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_buslocation_current_route_stop_and_more'),
        ('routes', '0007_stop_latitude_stop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='last_departure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='last_departure_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_departure_bus_locations', to='routes.routestop'),
        ),
    ]
