# Generated by Django 6.1.1 on 2026-09-24 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_buslocation_last_departure_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus', to=settings.AUTH_USER_MODEL),
        ),
    ]
