# Generated by Django 6.1.1 on 2026-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_bus_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buses/'),
        ),
    ]
