# Generated by Django 6.1.1 on 2026-09-25 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_bus_fare_bus_photo'),
        ('routes', '0007_stop_latitude_stop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('journey_date', models.DateField()),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('fare_per_passenger', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_to', to='routes.routestop')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='routes.busschedule')),
                ('source_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_from', to='routes.routestop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
