# Generated by Django 6.1.1 on 2026-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0010_alter_ticket_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
