# Generated by Django 6.1.1 on 2026-09-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0012_payment_razorpay_refund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='fare',
        ),
    ]
