# Generated by Django 6.1.1 on 2026-09-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0013_remove_bus_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=40, help_text='Maximum number of passengers the bus can carry.'),
        ),
    ]
