# Generated by Django 6.1.1 on 2026-10-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0014_bus_capacity'),
        ('routes', '0009_routestop_distance_from_start_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='destination_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_destinations', to='routes.routestop'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fare_per_passenger',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='journey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='passenger_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='routes.busschedule'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_sources', to='routes.routestop'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
