# Generated by Django 6.1.1 on 2026-10-01 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0015_payment_destination_stop_payment_fare_per_passenger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING', 'Booking'), ('PAYMENT', 'Payment'), ('DEPARTURE', 'Departure'), ('APPROACHING', 'Bus Approaching'), ('ARRIVED', 'Bus Arrived'), ('COMPLETED', 'Journey Completed'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='buses.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
